export const players = [
  {
    id: "marcus",
    name: "Marcus",
    username: "mt717",
    level: 37,
    team: 1,
    avatar: "/images/icons/tristana.jpg",
    summonerIcon: "/images/icons/summoner/marcus.jpg",
    banner: "/images/banner/tristana.jpg",
    skinName: "Tristana",
    rune: "/images/icons/runes/pta.jpg",
    summonerSpells: ["/images/icons/summoner-spells/flash.jpg", "/images/icons/summoner-spells/heal.jpg"],
    message:
    "Happy birthday Liner!!!\n\nHave fun, don't add to the population, don't subtract from the population and don't end up on the news in Korea!!\n\n안녕하세요, 당신은 제가 제일 좋아하는 털복숭이 친구예요.",
  },
  {
    id: "mete",
    name: "Mete",
    username: "Lobotomizer",
    level: 249,
    team: 1,
    avatar: "/images/icons/gragas.png",
    summonerIcon: "/images/icons/summoner/mete.jpg",
    banner: "/images/banner/gragas.jpg",
    skinName: "Gragas",
    rune: "/images/icons/runes/grasp.jpg",
    summonerSpells: ["/images/icons/summoner-spells/flash.jpg", "/images/icons/summoner-spells/teleport.jpg"],
    message:
    "Happy birthday mr sex tips!! I hope you have the bestest of times in Korea",
  },
  {
    id: "martin",
    name: "Martin",
    username: "Mighty",
    level: 246,
    team: 1,
    avatar: "/images/icons/talon.png",
    summonerIcon: "/images/icons/summoner/martin.jpg",
    banner: "/images/banner/talon.jpg",
    skinName: "Enduring Sword Talon",
    // roleIcon: "/images/icons/talon.png",
    rune: "/images/icons/runes/electrocute.jpg",
    summonerSpells: ["/images/icons/summoner-spells/flash.jpg", "/images/icons/summoner-spells/ignite.jpg"],
    message:
      "Happy birthday Linus ! 🎉 \nYou're 22 now it's time to pack it up lil bro🎒\n\nHave fun in Korea and bring back a wife",
  },
  {
    id: "darren",
    name: "Darren",
    username: "Derek Reborn",
    level: 142,
    team: 2,
    avatar: "/images/icons/sion.png",
    summonerIcon: "/images/icons/summoner/darren.jpg",
    banner: "/images/banner/sion.jpg",
    skinName: "Sion",
    rune: "/images/icons/runes/grasp.jpg",
    summonerSpells: ["/images/icons/summoner-spells/flash.jpg", "/images/icons/summoner-spells/teleport.jpg"],
    message:
      "Happy Birthday Linus!\n\n",
  },
  {
    id: "linus",
    name: "Linus",
    username: "的马西啊",
    level: 542,
    team: 2,
    avatar: "/images/icons/twitch.jpg",
    summonerIcon: "/images/icons/summoner/linus.jpg",
    banner: "/images/banner/twitch.jpg",
    skinName: "Twitch",
    rune: "/images/icons/runes/arcane-comet.jpg",
    summonerSpells: ["/images/icons/summoner-spells/flash.jpg", "/images/icons/summoner-spells/ignite.jpg"],
    message:
      "Lmao ur a twitch main"
  },
  {
    id: "andy",
    name: "Andy",
    username: "superchunguslove",
    level: 247,
    team: 2,
    avatar: "/images/icons/singed.jpg",
    summonerIcon: "images/icons/summoner/andy.jpg",
    banner: "/images/banner/singed.jpg",
    skinName: "Twitch",
    rune: "/images/icons/runes/arcane-comet.jpg",
    summonerSpells: ["/images/icons/summoner-spells/flash.jpg", "/images/icons/summoner-spells/ignite.jpg"],
    message:
      "happy birthday Linus you're 6pek greatest disciple"
  },
];

export const photos = [
  "/images/memories/linus9.jpg",
  "/images/memories/linus8.jpg",
  "/images/memories/linus7.jpg",
  "/images/memories/linus6.jpg",
  "/images/memories/linus5.jpg",
  "/images/memories/linus4.jpg",
  "/images/memories/linus3.jpg",
  "/images/memories/linus1.jpg",
  "/images/memories/linus2.jpg",
];
