import { asset } from "./utils";

export const players = [
    {
    id: "angus",
    name: "Angus",
    username: "XxLegendaryxX002",
    level: 25,
    team: 1,
    avatar: asset("/images/icons/garen.jpg"),
    summonerIcon: asset("/images/icons/summoner/angus.jpg"),
    banner: asset("/images/banner/garen.jpg"),
    skinName: "Garen",
    // roleIcon: asset("/images/icons/talon.png"),
    rune: asset("/images/icons/runes/electrocute.jpg"),
    summonerSpells: [asset("/images/icons/summoner-spells/flash.jpg"), asset("/images/icons/summoner-spells/ignite.jpg")],
    message:
      "Happy birthday Linus you’re old like the rest of us now can’t wait to be in the senior home soon together :))",
  },
  {
    id: "mete",
    name: "Mete",
    username: "Lobotomizer",
    level: 249,
    team: 1,
    avatar: asset("/images/icons/gragas.png"),
    summonerIcon: asset("/images/icons/summoner/mete.jpg"),
    banner: asset("/images/banner/gragas.jpg"),
    skinName: "Gragas",
    rune: asset("/images/icons/runes/grasp.jpg"),
    summonerSpells: [asset("/images/icons/summoner-spells/flash.jpg"), asset("/images/icons/summoner-spells/teleport.jpg")],
    message:
    "Happy birthday mr sex tips!! I hope you have the bestest of times in Korea",
  },
  {
    id: "martin",
    name: "Martin",
    username: "Mighty",
    level: 246,
    team: 1,
    avatar: asset("/images/icons/talon.png"),
    summonerIcon: asset("/images/icons/summoner/martin.jpg"),
    banner: asset("/images/banner/talon.jpg"),
    skinName: "Enduring Sword Talon",
    // roleIcon: asset("/images/icons/talon.png"),
    rune: asset("/images/icons/runes/electrocute.jpg"),
    summonerSpells: [asset("/images/icons/summoner-spells/flash.jpg"), asset("/images/icons/summoner-spells/ignite.jpg")],
    message:
      "Happy birthday Linus ! 🎉 \nYou're 22 now it's time to pack it up lil bro🎒\n\nHave fun in Korea and bring back a wife",
  },
  {
    id: "marcus",
    name: "Marcus",
    username: "mt717",
    level: 37,
    team: 1,
    avatar: asset("/images/icons/tristana.jpg"),
    summonerIcon: asset("/images/icons/summoner/marcus.jpg"),
    banner: asset("/images/banner/tristana.jpg"),
    skinName: "Tristana",
    rune: asset("/images/icons/runes/pta.jpg"),
    summonerSpells: [asset("/images/icons/summoner-spells/flash.jpg"), asset("/images/icons/summoner-spells/heal.jpg")],
    message:
    "Happy birthday Liner!!!\n\nHave fun, don't add to the population, don't subtract from the population and don't end up on the news in Korea!!\n\n안녕하세요, 당신은 제가 제일 좋아하는 털복숭이 친구예요.",
  },
  {
    id: "darren",
    name: "Darren",
    username: "Derek Reborn",
    level: 142,
    team: 2,
    avatar: asset("/images/icons/sion.png"),
    summonerIcon: asset("/images/icons/summoner/darren.jpg"),
    banner: asset("/images/banner/sion.jpg"),
    skinName: "Sion",
    rune: asset("/images/icons/runes/grasp.jpg"),
    summonerSpells: [asset("/images/icons/summoner-spells/flash.jpg"), asset("/images/icons/summoner-spells/teleport.jpg")],
    message:
      "Happy Birthday Linus!\n\n",
  },
  {
    id: "andy",
    name: "Andy",
    username: "superchunguslove",
    level: 247,
    team: 2,
    avatar: asset("/images/icons/singed.jpg"),
    summonerIcon: asset("images/icons/summoner/andy.jpg"),
    banner: asset("/images/banner/singed.jpg"),
    skinName: "Twitch",
    rune: asset("/images/icons/runes/arcane-comet.jpg"),
    summonerSpells: [asset("/images/icons/summoner-spells/flash.jpg"), asset("/images/icons/summoner-spells/ignite.jpg")],
    message:
      "happy birthday Linus you're 6pek greatest disciple"
  },
  {
    id: "linus",
    name: "Linus",
    username: "的马西啊",
    level: 542,
    team: 2,
    avatar: asset("/images/icons/twitch.jpg"),
    summonerIcon: asset("/images/icons/summoner/linus.jpg"),
    banner: asset("/images/banner/twitch.jpg"),
    skinName: "Twitch",
    rune: asset("/images/icons/runes/arcane-comet.jpg"),
    summonerSpells: [asset("/images/icons/summoner-spells/flash.jpg"), asset("/images/icons/summoner-spells/ignite.jpg")],
    message:
      "Lmao ur a twitch main"
  },
  {
    id: "ethan",
    name: "Ethan",
    username: "Maybechinese",
    level: 78,
    team: 2,
    avatar: asset("/images/icons/darius.jpg"),
    summonerIcon: asset("images/icons/summoner/ethan.jpg"),
    banner: asset("/images/banner/darius.jpg"),
    skinName: "Twitch",
    rune: asset("/images/icons/runes/arcane-comet.jpg"),
    summonerSpells: [asset("/images/icons/summoner-spells/flash.jpg"), asset("/images/icons/summoner-spells/ignite.jpg")],
    message:
      "Happy birthday pp, can’t wait to for our adventures in Asia"
  },
];

export const photos = [
  asset("/images/memories/linus9.jpg"),
  asset("/images/memories/linus8.jpg"),
  asset("/images/memories/linus7.jpg"),
  asset("/images/memories/linus6.jpg"),
  asset("/images/memories/linus5.jpg"),
  asset("/images/memories/linus4.jpg"),
  asset("/images/memories/linus3.jpg"),
  asset("/images/memories/linus1.jpg"),
  asset("/images/memories/linus2.jpg"),
];
